// <auto-generated />
using System;
using Confitec.WebAPI.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Confitec_Test.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20220821181255_AddTabelasbaseOnBD")]
    partial class AddTabelasbaseOnBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.Escolaridade", b =>
                {
                    b.Property<int>("IdEscolaridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscolaridade"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEscolaridade");

                    b.ToTable("TbEscolaridade");
                });

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.HistoricoEscolar", b =>
                {
                    b.Property<int>("IdHistoricoEscolar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoricoEscolar"), 1L, 1);

                    b.Property<string>("FileBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdHistoricoEscolar");

                    b.ToTable("TbHistoricoEscolar");
                });

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EscolaridadeId")
                        .HasColumnType("int");

                    b.Property<int?>("HistoricoEscolarId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("EscolaridadeId");

                    b.HasIndex("HistoricoEscolarId");

                    b.ToTable("TbUsuario");
                });

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.Usuario", b =>
                {
                    b.HasOne("Confitec.WebAPI.Infra.Data.Model.Escolaridade", "Escolaridade")
                        .WithMany("Usuarios")
                        .HasForeignKey("EscolaridadeId");

                    b.HasOne("Confitec.WebAPI.Infra.Data.Model.HistoricoEscolar", "Historico")
                        .WithMany("Usuarios")
                        .HasForeignKey("HistoricoEscolarId");

                    b.Navigation("Escolaridade");

                    b.Navigation("Historico");
                });

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.Escolaridade", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Confitec.WebAPI.Infra.Data.Model.HistoricoEscolar", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
